name: CI
on: [ push ]
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
        id: go
      - uses: actions/checkout@v2

      - run: go test ./...
